### ISSUE TITLE
Getting bookgui error

### ISSUE THREAD

**Issue by Fantom250YT** [JustixDevelopment/EazyNick#6]
[17:16:24 INFO]: Fantom250YT issued server command: /bookgui
[17:16:24 WARN]: java.lang.NoSuchFieldException: modifiers
[17:16:24 WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2416)
[17:16:24 WARN]: 	at net.dev.eazynick.utils.ReflectUtils.getField(ReflectUtils.java:38)
[17:16:24 WARN]: 	at net.dev.eazynick.utils.bookutils.NMSBookBuilder.create(NMSBookBuilder.java:32)
[17:16:24 WARN]: 	at net.dev.eazynick.commands.BookGUICommand.onCommand(BookGUICommand.java:52)
[17:16:24 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:16:24 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:16:24 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2011)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1822)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1775)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[17:16:24 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:835)
[17:16:24 WARN]: java.lang.NullPointerException
[17:16:24 WARN]: 	at net.dev.eazynick.utils.bookutils.NMSBookBuilder.create(NMSBookBuilder.java:33)
[17:16:24 WARN]: 	at net.dev.eazynick.commands.BookGUICommand.onCommand(BookGUICommand.java:52)
[17:16:24 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:16:24 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:16:24 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2011)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1822)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1775)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[17:16:24 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:835)
[17:16:24 WARN]: java.lang.NoSuchFieldException: modifiers
[17:16:24 WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2416)
[17:16:24 WARN]: 	at net.dev.eazynick.utils.ReflectUtils.getField(ReflectUtils.java:38)
[17:16:24 WARN]: 	at net.dev.eazynick.utils.bookutils.NMSBookUtils.lambda$0(NMSBookUtils.java:30)
[17:16:24 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[17:16:24 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[17:16:24 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:835)
[17:16:24 WARN]: java.lang.NullPointerException
[17:16:24 WARN]: 	at net.dev.eazynick.utils.bookutils.NMSBookUtils.lambda$0(NMSBookUtils.java:30)
[17:16:24 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[17:16:24 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
[17:16:24 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[17:16:24 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:835)

Thanks

**Comment by snakebiking49** [comment]
Did you ever find a solution?
